title: FLATCLASS - FLATfish Length and Thickness CLASification System by Artificial Intelligence
author: Javier Álvarez Osuna
logo: flatclass_logo.png
copyright: "Feeding Systems S.L. - GNU General Public License 2025"

execute:
  execute_notebooks: force
  kernel_name: python3
  timeout: 300
  allow_errors: false
  cache: ""

build:
  build_directory: "_build"
  exclude_patterns: 
    - "**.ipynb_checkpoints"
    - "**/.DS_Store"
  create_plots: true

latex:
  latex_documents:
    targetname: FLATCLASS.tex
  latex_engine: pdflatex
  remove_code_solution: true

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/jalosu/FFF-IA-book
  path_to_book: ""
  branch: master

html:
  extra_footer: ""
  use_issues_button: false
  use_repository_button: false
  use_edit_page_button: false
  use_download_button: false
  favicon: logo.png
  baseurl: ""
  analitics:
    google_analytics_id: ""

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - html_image
    - dollarmath
    - amsmath

sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex
    - myst_nb
  config:
    html_theme_options:
      use_download_button: false
    bibtex_reference_style: author_year  # Fuerza el formato "Autor et al., Año"
    bibtex_default_style: plain
    numfig: true
    numfig_format:
      figure: 'Figura %s'
      table: 'Tabla %s'
      code-block: 'Listado %s'   
    source_suffix: [".md", ".ipynb"]
    mathjax3_config:
      tex:
        inlineMath: [['$', '$'], ['\(', '\)']]

use_jupyterbook_latex: true
