@startuml
title Módulo de imagen (visión artificial)


start

:M2 - CALIBRADO;


partition "1) Preprocesado" {
  :Reducción de rudio;
  :Suavizado de bordes;
  :Normalización iluminación (CLAHE);
  :Conversión a HSV
  :Definición ROI (opcional);
  }

  partition "2) Segmentación" {
  :Definición de ROI;
  :Semillas /Umbrales;
  :GrabCut / Umbral + Morfología;
  :Máscara pez (fg_mask);
  if (¿Máscara válida?) then (Sí)
    :Seguir;
  else (No)
    :Error segmentación;
    stop
  endif
  }

  partition "3) Selección" {
  :Buscar contornos/componentes;
  if (¿Hay candidatos?) then (Sí)
    :Seleccionar principal (mayor área/ROI);
    :Verificar QC (área mínima, elongación, posición);
    if (¿QC OK?) then (Sí)
      :Contorno principal;
    else (No)
      :Rechazo QC;
      stop
    endif
  else (No)
    :Error sin objeto;
    stop
  endif
}

partition "4) Medición" {
  :PCA sobre puntos de controno;
  :Construir caja PCA y eje mayor;
  :Obtener dimensiones;
  if (¿Escala disponible?) then (Sí)
    :Convertir a mm/cm;
  else (No)
    :Medidas en px;
    stop
  endif
}

:M4 - SALIDA Y PERSISTENCIA;